# Agent Manager Configuration
# This file contains configuration settings for the Agent Manager

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  log_file: "logs/agent_manager.log"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Health Monitoring
health_check:
  interval: 30  # seconds
  agent_timeout: 300  # seconds
  max_retries: 3
  retry_delay: 1  # seconds

# Request Processing
request_processing:
  max_queue_size: 1000
  max_workers: 10
  request_timeout: 60  # seconds

# Agent Configuration
agents:
  website_researcher:
    max_concurrent_requests: 5
    capabilities: ["website_research"]
    priority: "normal"
    
  linkedin_analyzer:
    max_concurrent_requests: 5
    capabilities: ["linkedin_research"]
    priority: "normal"
    
  industry_problems_specialist:
    max_concurrent_requests: 3
    capabilities: ["industry_problems"]
    priority: "high"
    
  solutions_researcher:
    max_concurrent_requests: 3
    capabilities: ["ai_solutions"]
    priority: "high"
    
  tavily_researcher:
    max_concurrent_requests: 2
    capabilities: ["web_intelligence", "market_research"]
    priority: "high"
    
  email_generator:
    max_concurrent_requests: 5
    capabilities: ["email_generation"]
    priority: "normal"
    
  handoff_coordinator:
    max_concurrent_requests: 3
    capabilities: ["handoff_strategy", "priority_assessment"]
    priority: "high"
    
  research_reporter:
    max_concurrent_requests: 3
    capabilities: ["report_generation", "data_compilation"]
    priority: "normal"

# Performance Settings
performance:
  enable_caching: true
  cache_ttl: 3600  # seconds
  enable_monitoring: true
  metrics_retention: 86400  # seconds (24 hours)

# Security Settings
security:
  enable_rate_limiting: true
  max_requests_per_minute: 100
  enable_authentication: false  # Set to true when implementing auth
  allowed_origins: ["*"]

# Database Configuration (for future use)
database:
  enabled: false
  type: "sqlite"  # sqlite, postgresql, mysql
  connection_string: "sqlite:///agent_manager.db"
  pool_size: 5
  max_overflow: 10

# API Configuration
api:
  host: "localhost"
  port: 8000
  enable_swagger: true
  cors_enabled: true
  rate_limit_enabled: true

# Monitoring and Metrics
monitoring:
  enable_prometheus: false
  metrics_endpoint: "/metrics"
  health_check_endpoint: "/health"
  status_endpoint: "/status"
  
# Alerting
alerts:
  enabled: false
  email:
    smtp_server: "smtp.gmail.com"
    smtp_port: 587
    username: ""
    password: ""
    recipients: []
  
  slack:
    webhook_url: ""
    channel: "#alerts"
    
  thresholds:
    error_rate: 0.1  # 10%
    response_time: 30  # seconds
    queue_size: 100
    agent_health: 50  # minimum health score

# Development Settings
development:
  debug_mode: false
  enable_hot_reload: false
  log_requests: true
  mock_external_apis: false
