[project]
# Project name for Chainlit Cloud
name = "statdevs-sales-intelligence"

# Project description
description = "AI-powered lead research system for StatDevs - providing data engineering, AI/ML, and business intelligence solutions"

# Project tags
tags = ["sales", "ai", "data", "lead-research", "business-intelligence"]

# Project visibility (public or private)
visibility = "public"

# Project icon (emoji or URL)
icon = "🚀"

# Project color theme
primary_color = "#2563eb"

# Enable features
enable_chat_history = true
enable_chat_export = true
enable_telemetry = false

# UI customization
ui_name = "StatDevs Sales Intelligence"
ui_description = "Transform your leads into opportunities with AI-powered research and StatDevs solutions"

# Chat settings
chat_settings = {
    "model": "gpt-4",
    "temperature": 0.3,
    "max_tokens": 4000
}

# Deployment settings
[project.deploy]
# Auto-deploy on push
auto_deploy = true

# Environment variables
env_vars = [
    "OPENAI_API_KEY",
    "OPENAI_TRACE"
]

# Build settings
build_command = "pip install -r requirements.txt"
start_command = "chainlit run app.py --host 0.0.0.0 --port $PORT"
